#cloud-config

runcmd:
  - sudo rpm --import https://yum.corretto.aws/corretto.key
  - sudo curl -L -o /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo
  - sudo yum install -y java-17-amazon-corretto-devel
  - sudo adduser minecraft
  - sudo su
  - mkdir /opt/minecraft/
  - mkdir /opt/minecraft/server/
  - cd /opt/minecraft/server
  - wget https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar
  - sudo chown -R minecraft:minecraft /opt/minecraft/
  - sudo java -Xmx1024M -Xms1024M -jar server.jar nogui
  - sudo sed -i 's/eula=false/eula=true/' eula.txt