apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio-deployment
spec:
  selector:
    matchLabels:
      app: my-portfolio
  replicas: 1
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: my-portfolio-container
        image: registry.gitlab.com/exor420/modul-347
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-portfolio-service
spec:
  type: NodePort
  selector:
    app: my-portfolio
  ports:
  - name: http
    port: 80
    targetPort: 80
